# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paperclipdb}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Martin Caruso}]
  s.date = %q{2011-07-04}
  s.description = %q{Database storage support for paperclip file attachment plugin}
  s.email = %q{caruso.martin@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".loadpath",
    ".project",
    "MIT-LICENSE",
    "README",
    "Rakefile",
    "VERSION",
    "app/controllers/paperclipdb/attachments_controller.rb",
    "app/models/paperclipdb/attachment.rb",
    "config/routes.rb",
    "db/migrate/20100906021538_attachments.rb",
    "generators/paperclipdb/USAGE",
    "generators/paperclipdb/paperclipdb_generator.rb",
    "init.rb",
    "install.rb",
    "lib/paperclipdb.rb",
    "lib/paperclipdb/storage.rb",
    "lib/tasks/paperclipdb.rake",
    "paperclipdb.gemspec",
    "test/paperclipdb_test.rb",
    "test/test_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/mcaruso85/paperclipdb}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Database storage support for paperclip file attachment plugin.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
    else
      s.add_dependency(%q<paperclip>, [">= 0"])
    end
  else
    s.add_dependency(%q<paperclip>, [">= 0"])
  end
end

